name: Release

on:
  push:
    tags: '**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          registry-url: https://registry.npmjs.org
      - uses: oven-sh/setup-bun@v2

      - run: |
          [[ $TAG =~ ^((@.+?\/)?(.+))@(.+)$ ]]
          PACKAGE=${BASH_REMATCH[1]}
          DIR=${BASH_REMATCH[3]}
          VERSION=${BASH_REMATCH[4]}
          echo -e "DIR=$DIR\nPACKAGE=$PACKAGE\nVERSION=$VERSION" >> $GITHUB_ENV

      - run: bun i
      - run: bun lint
      - run: bun run build

      - run: bun pm pack && npm publish *.tgz
        working-directory: packages/${{ env.DIR }}
      - run: gh release create $TAG --title $TAG --draft
        working-directory: packages/${{ env.DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}